name: Mirror and run GitLab CI

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Redefine branch on pull_request
        if: github.event_name == 'pull_request'
        run: |
          echo "current_branch=$(echo ${{ github.head_ref }})" >> $GITHUB_ENV

      - name: Redefine branch on push
        if: github.event_name == 'push'
        run: |
          echo "current_branch=$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')" >> $GITHUB_ENV

      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@0.6
        with:
          args: "https://gitlab.desy.de/dcache/dcache"
        env:
          FOLLOW_TAGS: "true"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab.desy.de"
          GITLAB_USERNAME: "dcache"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "21"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POLL_TIMEOUT: 60
          GITHUB_REF_NAME: ${{ env.current_branch }} # Overwrite the branch name for pull requests
