name: Mirroring to Gitlab

on: [push, delete, pull_request]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    if: github.repository == 'dcache/dcache'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.desy.de:dcache/dcache.git
          ssh_private_key:        
            ${{ secrets.REPOSYNC_SSH_PRIVATE_KEY }}
